### PR TITLE
Add SecretSanta class.

### PR DESCRIPTION
**Pull request by Pasakinskas**
I did some work implementing the SecretSanta class.

### CODE REVIEW

**Comment by AndDauJA** [comment]
ok

**Review by AntiQnis — APPROVED** [review]
gerai YRA cia viskas 🗡️  :D

**Review by Vaidas196 — APPROVED** [review]
very nice

**Review by AndDauJA — APPROVED** [review]
ok supratau

**Review by karoliskaralaitis — APPROVED** [review]
I approve

**Review by DovydasBerzanskas — COMMENTED** [review]
Gražiausias kodas kokį esu matęs

**Review by martis1877 — COMMENTED** [review]
Atrodo gražiai

**Comment by ZydrunasN** [comment]
approvinu

**Comment by TeodorasKyborgas** [comment]
me too

**Comment by ernestaskriskus** [comment]
Yo

**Comment by Ingridamot** [comment]
Super

**Pull request merged**
